// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DepDiary.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DepDiary.Entities.Configurations
{
    public partial class NotesConfiguration : IEntityTypeConfiguration<Notes>
    {
        public void Configure(EntityTypeBuilder<Notes> entity)
        {
            entity.HasKey(e => e.NoteId).HasName("PK__Notes__EACE355F95ABFF17");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Title).HasMaxLength(255);

            entity.HasOne(d => d.Diary).WithMany(p => p.Notes)
            .HasForeignKey(d => d.DiaryId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Notes__DiaryId__3D5E1FD2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Notes> entity);
    }
}
