// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DepDiary.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DepDiary.Entities.Configurations
{
    public partial class NotesConfiguration : IEntityTypeConfiguration<Notes>
    {
        public void Configure(EntityTypeBuilder<Notes> entity)
        {
            entity.HasKey(e => e.NoteId).HasName("PK__Notes__EACE355F95ABFF17");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Title).HasMaxLength(255);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Notes> entity);
    }
}
