// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DepDiary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DepDiary.Models.Configurations
{
    public partial class UsersConfiguration : IEntityTypeConfiguration<Users>
    {
        public void Configure(EntityTypeBuilder<Users> entity)
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4CD464EE8F");

            entity.Property(e => e.Email)
            .IsRequired()
            .HasMaxLength(255);
            entity.Property(e => e.Password)
            .IsRequired()
            .HasMaxLength(255);
            entity.Property(e => e.Username)
            .IsRequired()
            .HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Users> entity);
    }
}
